### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by KawaiiNahida** [Sysca11/bdlauncher#1]
在1.9.0.25版本中，会导致命令失效
[2019-02-09 11:44:22 INFO] Player connected: WangYneos, xuid:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by ghost** [comment]
请问是执行哪个命令时失效？因为我本地环境是1.8服务器

**Comment by KawaiiNahida** [comment]
所有命令，除了quit，在1.9上完全失效，在后台ban了人，那个人还玩的挺high

**Comment by ghost** [comment]
服务器自带的命令也失效了？

**Comment by KawaiiNahida** [comment]
对的，像gamemode gamerule都失效了

**Comment by ghost** [comment]
（稍等我测试一下

**Comment by ghost** [comment]
我这指令是正常的，估计是单个指令的问题

**Comment by ghost** [comment]
可以麻烦测试一下，执行完哪个指令之后服务器卡死，还是说玩家一进来就卡死吗

**Comment by KawaiiNahida** [comment]
我这里是不卡死，但是命令失效，比如 gamemode 1 @a 那么一分钟之后所有人都还是生存

**Comment by KawaiiNahida** [comment]
我晚点再在VMware上测试下

**Comment by ghost** [comment]
我本地没办法复现那个bad_alloc,估计是微软又乱改了现在没办法获取玩家名字

**Comment by ghost** [comment]
本地测试过了，等我push -f,,,
