### ISSUE TITLE
领地指令无反应

### ISSUE THREAD

**Issue by Redbeanw44602** [Sysca11/bdlauncher#10]
我输入
/land start
/land end
/land buy
等等指令，都不会在聊天栏显示出来。当然，也不会完成购买。
我的Minecraft版本是1.10，使用land1.10.so
望尽快修复！！
如果可以，麻烦作者留个QQ？我的QQ:2403393945

**Comment by ghost** [comment]
抱歉1.10的第三方编译版本有问题，我本地编译环境已经删了
