### ISSUE TITLE
[MOD] err loading ./mods/bear.so handle (nil) ./mods/bear.so: undefined symbol: _ZNK13ItemStackBase11getUserDataEv

### ISSUE THREAD

**Issue by mclauncherlinux** [Sysca11/bdlauncher#17]
[MOD] err loading ./mods/bear.so handle (nil) ./mods/bear.so: undefined symbol: _ZNK13ItemStackBase11getUserDataEv

**Comment by ghost** [comment]
for server version 1.13 only

**Comment by mclauncherlinux** [comment]
@Sysca11 how can people earn money? How is new money generated? where can I edit starter money balance  for player?

**Comment by mclauncherlinux** [comment]
and where can I change prices for land

**Comment by KawaiiNahida** [comment]
maybe you can use 
/money set [playername] [amount]
To set money easily for a player
And you can edit the price in mod/land/land.cpp
Then run ./cmp.sh to generate a edited land.so and get the file in out/land.so
