### ISSUE TITLE
entities can be spawned through dispensers/hoppers

### ISSUE THREAD

**Issue by mclauncherlinux** [Sysca11/bdlauncher#25]
yea its still possible to bypass the anti spawn through hoppers/dispensers. my own vanilla fix is disabling off-hand. search for dakonblackrose in YT, he made a tutorial how to do it

**Comment by ghost** [comment]
Do you mean put spawneggs into dispensers to bypass the useitem limits in mod antbear?I'm considering rejecting players' putting spawneggs on hand.

**Comment by mclauncherlinux** [comment]
yea, correctly. they can spawn mobs using dispensers with spawn eggs

**Comment by mclauncherlinux** [comment]
disabling off-hand is just a fix to prevent cheaters cheating eggs in off hand, however I heard there are hack clients that can cheat items just through a command that's client sided?....

**Comment by ghost** [comment]
item cheating is a mojang-related bug.In fact,there are several ways to get items(offhand hack,crafting table hack,etc.).
mojang did try to fix this bug,however,there are too many attack surfaces.
Disabling offhand is okay.but you can still get spawneggs by modifying client crafting receipts(like 1xdirt to 64 x spawn eggs)

**Comment by mclauncherlinux** [comment]
yea agreed... its sad that its not possible to run a public vanilla server . xDD there are always hackers :/

**Comment by mclauncherlinux** [comment]
btw bdlauncher performs pretty good. I have a public server with 50/50 players without lag :) thank you very much for this awesome project I think it fits ideally if you want run a whitelisted server but at the same time you want invite "every person" without to need to worry getting griefed by every random. with a little bit moderation a server using bdlauncher can work pretty good

**Comment by ghost** [comment]
Glad to see bdl working well on your server. :D
Offhand item hack and banitem might be fixed at next commit.(Because mojang changes their inventory API so frequently.It's really a hard job to maintain a anticheat mitigation plugin)

**Comment by Sysca11** [comment]
Glad to see bdl working well on your server. :D
Offhand item hack and banitem might be fixed at next commit.(Because mojang changes their inventory API so frequently.It's really a hard job to maintain a anticheat mitigation plugin)
