### ISSUE TITLE
新的插件创意：关于“窗口”插件

### ISSUE THREAD

**Issue by leoweyr** [Sysca11/bdlauncher#27]
一、插件名称
window

二、如何工作及其表现
1.开发者制作一个框架，由需求者自定义实质内容。相当于插件开发者制作plugin，其他需求者根据实际将其做成该plugin的addon
2.游戏内执行一条命令，召唤该窗口。执行命令及命令描述没有唯一，由需求者自定义。但其基本结构为①执行指令+ture（打开窗口）②执行指令+false（关闭窗口）
3.窗口由本身样式及其功能组件组成。游戏内使用窗口即是浏览或使用其中的组件。窗口可视区域分为标题区和组件区
4.本身样式即窗口大小、窗口背景透明度。开发者在原始框架中注释窗口最大大小及标准大小
5.组件即纯文字段、图片、按钮、输入框。可以理解为像html那样
6.编辑窗口组件像编辑html那样的标签化
7.按钮即点击执行一条链指令或跳转至某个url。按钮大小和透明度可调，其中可视的信息部分可以加入文字或图片或图文并茂。一条链指令要支持像命令方块逻辑那样的“有条件的”和“无条件的”，最好也支持目标选择器
8.输入框即动态变量。某个输入框的变量可以在插件文件中定义为某个值，如a输入框的变量定义为b，当玩家在窗口实时输入一个实际字段“c”时，该变量就会实时变成“c”。变量可以在命令中使用，（接着前面给变量b赋的实际自动为“c”）如say b，则实际执行的指令为say c。通过这样与按钮的执行命令功能再结合其他插件可以做成实时的可变功能，比如添加好友、cdk兑换、购买物品数量等
9.需求者做出的addon像插件那样，一个服可以装多个“window”插件，需求者改插件名即可不冲突。基本框架插件名为“window”
 
三、拓展意义
1.插件开发者开发一个基本框架，由需求者根据实际需求做出千万种可能的addon，并且降低开发门槛，有助于大部分无相关C++能力的腐竹。
2.该插件可以自由变换成具有新闻公告、RPG兑换、游戏商城等功能的addon

四、对插件开发者的留言
如果你要对该插件标明作者信息，希望你能标上“创意来源于雷欧炜翼”（英文：Creativity comes from leoweyr），这将成为我不断创作插件创意的动力。最后希望你根据我创意做出来的插件能成为你的代表作或满意或得意之作。
我也不知道为什么不能上传图片，我将以pdf的方式通过QQ私发给你。

**Comment by KawaiiNahida** [comment]
你好,GUI.so已实现以上功能
可以参考cmdhelp.cpp参照用法
如果需要一些简单快捷按钮可以用cmdhelp
有一些插件已经对gui.so适配
可以试试在一些命令后加gui
如/home gui

**Comment by leoweyr** [comment]
我知道gui已经实现，但是可以有我说的组件吗

**Comment by leoweyr** [comment]
gui目前好像只能规定大小？

**Comment by KawaiiNahida** [comment]
目前Sysca11完成的就只有
gui_GetInput()
gui_Buttons()
gui_ChoosePlayer()
![图片](https://user-images.githubusercontent.com/42824603/69472154-7df17400-0de1-11ea-8010-1445677bb5b3.png)

**Comment by KawaiiNahida** [comment]
按钮,输入框等大小是固定的

**Comment by KawaiiNahida** [comment]
你可以在qq群at他

**Comment by leoweyr** [comment]
其实我这个灵感是根据gui写出来的，写出更加强大，更加自定义的功能。

**Comment by KawaiiNahida** [comment]
虽然大小不可调整,但是也还是能实现相关功能的,只是实现较复杂.

**Comment by leoweyr** [comment]
假如插件作者能够根据我那个上面的创意进化一下插件，那么这个新的插件就有非常非常多的拓展性了。

**Comment by leoweyr** [comment]
我之前已经跟插件作者说，我写创意他来开发插件。

**Comment by leoweyr** [comment]
假如能够实现我上面创意所提及到的插件，那么我就能在addon中开发一个能有对话框的npc

**Comment by KawaiiNahida** [comment]
不如去QQ聊吧,Github不方便

**Comment by KawaiiNahida** [comment]
955765957

**Comment by KawaiiNahida** [comment]
建议去群里找群主
