### ISSUE TITLE
[MOD] err loading ./mods/land.so handle (nil) ./mods/land.so: undefined symbol: _Z10reg_attackSt8functionIFbP12ServerPlayerP5ActorEE

### ISSUE THREAD

**Issue by mclauncherlinux** [Sysca11/bdlauncher#28]
[MOD] err loading ./mods/land.so handle (nil) ./mods/land.so: undefined symbol: _Z10reg_attackSt8functionIFbP12ServerPlayerP5ActorEE land.so not working in 1.13.3

**Comment by leoweyr** [comment]
。。。。

**Comment by leoweyr** [comment]
。。。。

**Comment by KawaiiNahida** [comment]
it work well on 1.13.3
![图片](https://user-images.githubusercontent.com/42824603/69476731-ba8c9200-0e18-11ea-93e1-b32358644a36.png)

**Comment by leoweyr** [comment]
Sir,you see that it bugs on the "land" plugin.

**Comment by leoweyr** [comment]
you may change something and make it error

**Comment by KawaiiNahida** [comment]
![图片](https://user-images.githubusercontent.com/42824603/69476834-dd6b7600-0e19-11ea-9755-28a39023a288.png)
I know, and it really work well on BedrokServer 1.13.3

**Comment by leoweyr** [comment]
Try to fitting the plugins or redownload again.

**Comment by KawaiiNahida** [comment]
try git pull again

**Comment by mclauncherlinux** [comment]
hmm alright, I will do it

**Comment by ghost** [comment]
codebase is being reconstructed,so you may not use old base.so with new plugins

**Comment by mclauncherlinux** [comment]
using the latest version
enabling ./mods/opti.so entry opti_init
[OPTI] Config JSON ERROR!

**Comment by mclauncherlinux** [comment]
I did not modify any file or config

**Comment by KawaiiNahida** [comment]
you might need run
cp -a ./bdlauncher/config ./

**Comment by mclauncherlinux** [comment]
[OPTI] loaded! V2019-11-21
[MOD] err loading ./mods/bear.so handle (nil) ./mods/bear.so: undefined symbol: _Z15reg_player_leftSt8functionIFvP12ServerPlayerEE
I get this error now. what is even bear.so?

**Comment by KawaiiNahida** [comment]
run these command to download latest loader and mod.
I can solve most problem
(this will not remove any player data)
<pre>
rm -rf ./mods
rm -rf ./config
git clone https://github.com/sysca11/bdlauncher -b master --depth=1
mkdir mods
cp -a ./bdlauncher/out/* ./mods
cp -a ./bdlauncher/mod.list ./mods
cp -a ./bdlauncher/config .
LD_LIBRARY_PATH=. LD_PRELOAD=./mods/a.so ./bedrock_server
</pre>

**Comment by ghost** [comment]
try updatimg your base.so

**Comment by mclauncherlinux** [comment]
its working now, many thanks :D

**Comment by mclauncherlinux** [comment]
is /shop removed?

**Comment by KawaiiNahida** [comment]
yes ,but you can use /cmd command to do something that /shop can do
(you need config file cofig/cmdhelp.config to config /cmd before use)

**Comment by KawaiiNahida** [comment]
If you can use QQ to contact with us it's better

**Comment by mclauncherlinux** [comment]
ok how to register QQ  without mobile phone I am on pc rn

**Comment by mclauncherlinux** [comment]
oh yea an android emulator.. can you send me the download of the app (android)

**Comment by KawaiiNahida** [comment]
https://qd.myapp.com/myapp/qqteam/AndroidQQ/mobileqq_android.apk

**Comment by KawaiiNahida** [comment]
if it is diffcult for you ,you can still use github to contact with us

**Comment by mclauncherlinux** [comment]
I need that people can sell and buy  1 diamond for 100 ingame money

**Comment by mclauncherlinux** [comment]
is there a way to block nuker (Horion Client)

**Comment by Sysca11** [comment]
whats that？------------------ 原始邮件 ------------------
发件人: "mclauncherlinux"<notifications@github.com>
发送时间: 2019年11月23日(星期六) 晚上8:59
收件人: "Sysca11/bdlauncher"<bdlauncher@noreply.github.com>;
抄送: "Sysca11"<3321056730@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [Sysca11/bdlauncher] [MOD] err loading ./mods/land.so handle(nil) ./mods/land.so: undefined symbol:_Z10reg_attackSt8functionIFbP12ServerPlayerP5ActorEE (#28)



is there a way to block nuker (Horion Client)
 
&mdash;

**Comment by Sysca11** [comment]
demo config for shop，lottery will be uploaded later------------------ 原始邮件 ------------------
发件人: "mclauncherlinux"<notifications@github.com>
发送时间: 2019年11月23日(星期六) 晚上8:39
收件人: "Sysca11/bdlauncher"<bdlauncher@noreply.github.com>;
抄送: "Sysca11"<3321056730@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [Sysca11/bdlauncher] [MOD] err loading ./mods/land.so handle(nil) ./mods/land.so: undefined symbol:_Z10reg_attackSt8functionIFbP12ServerPlayerP5ActorEE (#28)



I need that people can sell and buy diamonds for 100 in game currency
 
&mdash;

**Comment by mclauncherlinux** [comment]
https://horionclient.eu its one of the hack clients that is able to destroy 1000 blocks in 1 hit

**Comment by mclauncherlinux** [comment]
Mojang/microsoft is refusing since many months to patch this I reported it many times already

**Comment by mclauncherlinux** [comment]
{"type":"define",
"name":"exchange money to diamonds",
"cond":"money rd %name% 100",
"cmd":"give %name% diamond 1"}

ok I got this  this should take money away for diamonds, correct? but how can I sell money for for diamonds?

**Comment by ghost** [comment]
use /clear twice to detect and remove item. new version of cmdhelper will be release soon(and new config format),so it's not advised to write config for production use now.------------------ 原始邮件 ------------------
发件人: "mclauncherlinux"<notifications@github.com>
发送时间: 2019年11月23日(星期六) 晚上10:03
收件人: "Sysca11/bdlauncher"<bdlauncher@noreply.github.com>;
抄送: "Sysca11"<3321056730@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [Sysca11/bdlauncher] [MOD] err loading ./mods/land.so handle(nil) ./mods/land.so: undefined symbol:_Z10reg_attackSt8functionIFbP12ServerPlayerP5ActorEE (#28)



{"type":"define",
 "name":"exchange money to diamonds",
 "cond":"money rd %name% 100",
 "cmd":"give %name% diamond 1"}
 
ok I got this  this should take money away for diamonds, correct? but how can I sell diamonds for money?
 
&mdash;

**Comment by mclauncherlinux** [comment]
alright, thanks :)

**Comment by leoweyr** [comment]
yeah

**Comment by leoweyr** [comment]
Sir,can you use C++？We need a plugins maker

**Comment by mclauncherlinux** [comment]
oof no I am not a cpp dev, however I started to learn cpp a few weeks ago @leoweyr
