### ISSUE TITLE
新的插件创意：关于“目标选择器”插件

### ISSUE THREAD

**Issue by leoweyr** [Sysca11/bdlauncher#29]
一、插件名称
targetselectorplus

二、如何工作及其表现
1.新增@l，解释是last entity
2.@l像其他目标选择器(@s、@a、@r、@p、@e)一样,可以用于单条指令、命令方块、function包等普通目标选择器可以做到的事情
3.在一条链的指令中，其中一条指令的@l是选中该链中这条指令的前一条指令成功执行的目标。当@l用于该链第一条指令时，则不会选中任何目标。

三、拓展意义
1.具体地对一个详细的目标进行追踪，准确将指定目标完成预定的无限指令
2.具有“选择筛选功能”，当某目标不能被“上一条指令”成功选中执行时，就会破“淘汰”，被“筛选”掉

四、对插件开发者留言
如果你要对该插件标明作者信息，希望你能标上“创意来源于雷欧炜翼”（英文：Creativity comes from leoweyr），这将成为我不断创作插件创意的动力。最后希望你根据我创意做出来的插件能成为你的代表作或满意或得意之作。

**Comment by ghost** [comment]
mojang related.
