### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by Redbeanw44602** [Sysca11/bdlauncher#3]
好像只能买1个方块......（最新1.9）多了就会失败，只买一个3x3购买成功，扣了10 但是大了就会失败

**Comment by ghost** [comment]
钱不够吧

**Comment by Redbeanw44602** [comment]
我给自己set了一百万，还是介个样子。
不知道是不是我的方法不对，我是用鼠标右键圈地，3x3购买成功。

**Comment by ghost** [comment]
/money query查下剩余钱

圈地失败输出的提示是啥 可以截图下吗

**Comment by ghost** [comment]
我也是这样 failed buying land

**Comment by ghost** [comment]
确定一下领地没有和不属于自己的领地重叠

**Comment by ghost** [comment]
玩家先/money query查钱，然后看看圈的地有没有和不属于自己的领地有重叠的 @643822883

**Comment by ghost** [comment]
确定没有重叠，老哥方便留下qq吗

**Comment by Sysca11** [comment]
1710637899

**Comment by ghost** [comment]
申请了

**Comment by ghost** [comment]
领地重叠判断的问题，应该修复了

**Comment by KawaiiNahida** [comment]
还是不行
failed buying land.Select start and end plz

**Comment by ghost** [comment]
@WangYneos /land start 点地，/land end点地然后才能buy

**Comment by KawaiiNahida** [comment]
对啊

**Comment by ghost** [comment]
服务器发一下？
试试点地的时候手里拿个东西

**Comment by KawaiiNahida** [comment]
xsba.mcwd.ml:19134
你的Xbox名发一下

**Comment by Sysca11** [comment]
cpera

**Comment by KawaiiNahida** [comment]
加白名单了

**Comment by ghost** [comment]
网不行根本进不去 输完指令之后有显示了再点地，还有就是bin更新了 重新下载一下

**Comment by KawaiiNahida** [comment]
还是不行，左键还是右键点

**Comment by ghost** [comment]
右键

**Comment by ghost** [comment]
include路径自己修复 在/mods/include
cmp.sh自己得改一下

**Comment by KawaiiNahida** [comment]
ok，谢谢

**Comment by KawaiiNahida** [comment]
qaq我是学Java的
g++不知道咋用

yneos@WangYneos-PC:/mnt/c/Users/WangYneos/Documents/GitHub/bdlauncher/mods/land$ ls
cm.sh  cmp.sh  include  main.cpp

g++ main.cpp -o land.so -I /mnt/c/Users/WangYneos/Documents/GitHub/bdlauncher/mods/land/include/

**Comment by KawaiiNahida** [comment]
yneos@WangYneos-PC:/mnt/c/Users/WangYneos/Documents/GitHub/bdlauncher/mods/land$ ./cm.sh
main.cpp:8:10: fatal error: minecraft/command/Command.h: No such file or directory
 #include <minecraft/command/Command.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by KawaiiNahida** [comment]
可以帮忙看看吗

**Comment by ghost** [comment]
cmp.sh g++参数加上 -I include目录路径

**Comment by KawaiiNahida** [comment]
g++ main.cpp -o land.so -I /mnt/c/Users/WangYneos/Documents/GitHub/bdlauncher/mods/land/include/
我改成这样了，但是还是不行

**Comment by ghost** [comment]
还得改一下文件include的路径，有的我写的是相对路径 你看着.h的名字找一下 人工改改吧

**Comment by KawaiiNahida** [comment]
哦哦，谢谢，我去下载codeHZ的BDSM去

**Comment by ghost** [comment]
头文件不是原版bdsm的头文件
