### ISSUE TITLE
Server in booming

### ISSUE THREAD

**Issue by Redbeanw44602** [Sysca11/bdlauncher#30]
服务器经常未正常关闭。不知道怎么肥四
![Screenshot_20191128_210101](https://user-images.githubusercontent.com/29711228/69808364-45f39200-1222-11ea-8d98-4557c5e01c26.jpg)

**Comment by Sysca11** [comment]
mojang related bug------------------ 原始邮件 ------------------
发件人: "Redbeanw！"<notifications@github.com>
发送时间: 2019年11月28日(星期四) 晚上9:00
收件人: "Sysca11/bdlauncher"<bdlauncher@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Sysca11/bdlauncher] Server in booming (#30)



&#x670D;务器经常未正常关闭。不知道怎么肥四
 
 
&mdash;

**Comment by ghost** [comment]
mojang related bug.
