### ISSUE TITLE
bdlauncher for 1.14 seems to be stable and working

### ISSUE THREAD

**Issue by mclauncherlinux** [Sysca11/bdlauncher#34]
just letting you know that my 1.14 server with bdlauncher runs stable without issues and 1.14 does not have huge protocol changes

**Comment by Sysca11** [comment]
okay,thanks bro :D------------------ 原始邮件 ------------------
发件人: "mclauncherlinux"<notifications@github.com>
发送时间: 2019年12月11日(星期三) 下午4:48
收件人: "Sysca11/bdlauncher"<bdlauncher@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Sysca11/bdlauncher] bdlauncher for 1.14 seems to be stable andworking (#34)



just letting you know that my 1.14 server with bdlauncher runs stable without issues and 1.14 does not have huge protocol changes
 
&mdash;
