### ISSUE TITLE
三个建议，附带一个bug

### ISSUE THREAD

**Issue by suoyukii** [Sysca11/bdlauncher#39]
## 建议
* 聊天记录、违禁物记录、玩家出入服务器记录 单独保存成一个log文件
* 语言文件从代码中分离出来，改为配置加载，语言在配置中自行设置，因为服务器是英文的，玩家可能是中国的
* 移除掉这句话，因为不管是服务器还是客户端都已经有一句了，加了这句话就重复说两次了
![image](https://user-images.githubusercontent.com/16282726/71500554-6b66d080-28a0-11ea-85fa-094152dc5ac2.png)
## BUG
* 所有玩家的名字都变成了 [ADMIN] c
![image](https://user-images.githubusercontent.com/16282726/71500468-188d1900-28a0-11ea-9c5f-e9aea2d9a5b8.png)

**Comment by ghost** [comment]
Language won't be moved to config jsons.It will be placed at headers,which you can specific language at compile-time.
"xxx" joined is a join hook of cmdhelper,you can delete it in config/cmd.json
 {
        "type":"join",
        "cmd":"sched 10 %name% \"say §b $name$ joined this server\""
    },

**Comment by suoyukii** [comment]
- 还有一个bug
- 非OP玩家无法移动背包中的物品

**Comment by ghost** [comment]
fixed commit #185bdaf
