### ISSUE TITLE
请问一下还有什么依赖

### ISSUE THREAD

**Issue by KawaiiNahida** [Sysca11/bdlauncher#4]
yneos@WangYneos-PC:/mnt/c/Users/WangYneos/Documents/GitHub/bdlauncher/mods/land$ sudo ./cm.sh
main.cpp:8:10: fatal error: minecraft/command/Command.h: No such file or directory
 #include <minecraft/command/Command.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by KawaiiNahida** [comment]
我想汉化一下

**Comment by ghost** [comment]
无依赖 头文件在mods.h和mods/include 有的头文件路径打错了

**Comment by KawaiiNahida** [comment]
3	24	C:\Program Files (x86)\Dev-Cpp\MinGW64\lib\gcc\x86_64-w64-mingw32\4.9.2\include\minecraft\net\NetworkIdentifier.h	[Error] sys/socket.h: No such file or directory

**Comment by ghost** [comment]
linux环境的.

**Comment by KawaiiNahida** [comment]
![screenshot_20190222-192441](https://user-images.githubusercontent.com/42824603/53239686-92c89c00-36d7-11e9-8e44-8475540262ef.png)

**Comment by ghost** [comment]
重新下载下cmp.sh,你这cmp.sh好像是坏的
