### ISSUE TITLE
Money Plugin Bug Fixing Version!(Chinese)(Can download)(Don't close)

### ISSUE THREAD

**Issue by China-GWY** [Sysca11/bdlauncher#47]
Bugs Fixed:
1.Fixed a bug what the server crashed when you executed the '/money add' command
2.Fixed a bug what allowed you to set a player's money from positive number to negative
3.Fixed a  bug what the server crashed when you executed the '/money paygui' command in console
4.Fixed a bug what a big part of commands can only be used in game,if you use them in  console,the server will crash!
optimizations:
1.It has been sinicized!
2.If players' input are not right,plugins will tell them ----"[MONEY]用法错误，输入/money help查看用法" 
3.Subcommand "help" added
4.Command 'reload_command' has changed to "money reload"
5.Permissions changed more rigorous
6.Texts changed more colorful
7.Many things that shouldn't be able to be performed in the console are all Limited
8.Execution time is shortened but not obvious
9.Limit the command 'money pay' can't pay yourself
10.Command name slightly adjusted
11.Many small details have been optimized
download: https://pan.baidu.com/s/1gZlYzbGZnemxmrTRLUD2aw
password: jx6g
You can use pandownload(www.pandownload.com) to download it quickly!
Supported by Candy Technology

**Comment by China-GWY** [comment]
Don't close it,Let more people see it,It is a useful plugin!
别关闭，让更多的人看到他，这是一个有用的东西

**Comment by ghost** [comment]
will merge soon.
Could you please open a pull request instead?

**Comment by mclauncherlinux** [comment]
nice gonna try it

**Comment by KawaiiNahida** [comment]
if you fixed some bugs， you can make a pull request

**Comment by China-GWY** [comment]
> will merge soon.
> Could you please open a pull request instead?



> if you fixed some bugs， you can make a pull request

Yes,I'd like it!But how can I do it!

**Comment by China-GWY** [comment]
How to open a pull request？
这破玩意怎么打开请求？

> will merge soon.
> Could you please open a pull request instead?

**Comment by l0nGYear** [comment]
> How to open a pull request？
> 这破玩意怎么打开请求？
> 
> > will merge soon.
> > Could you please open a pull request instead?

As a programmer, I think this is a very good project, but it is a pity that the developer of this project do not have the ability to lead this project. If you are also interested in such a project, I hope to work with you to develop a similar project.

**Comment by leoweyr** [comment]
it is some vurise?

**Comment by KawaiiNahida** [comment]
no
