### ISSUE TITLE
A man says your bdlauncher has trojan horse！I'm very angry that they think so!

### ISSUE THREAD

**Issue by China-GWY** [Sysca11/bdlauncher#48]
![2BA32FFC1E15B95131985394C100D743](https://user-images.githubusercontent.com/54971333/72030040-cfd35800-32c2-11ea-953e-d72ca2b4fd19.jpg)
Look at this!
You must talk about with them!
Please call 17054536233 in QQ

**Comment by China-GWY** [comment]
![2BA32FFC1E15B95131985394C100D743](https://user-images.githubusercontent.com/54971333/72030137-11fc9980-32c3-11ea-8415-91cd7cfb91bd.jpg)

**Comment by ghost** [comment]
I DONT know what do you mean.And I dont think I have the obligation to call a unknown phone number for you.
I'm not interested in arguing with you and your partner.
If you dont like this repo,alt+f4 plz.Dont complain of the SPONSOR like your partners if you still have conscience.
If you mean it's a torjan,yes,it WILL ENCRYPT ALL UR FILES AND FUCK UR ROOT USER.
So can you stop here?Did I ask any bitcoin form U?If not,please GET OUT and stop POISONING issues by using Chinese rude words or Chinglish(DO U THINK I CANT UNDERSTAND CHINESE?) and egging me on to have a argument with others.
Stop spamming,I beg U.

**Comment by China-GWY** [comment]
> I DONT know what do you mean.And I dont think I have the obligation to call a unknown phone number for you.
> I'm not interested in arguing with you and your partner.
> If you dont like this repo,alt+f4 plz.Dont complain of the SPONSOR like your partners if you still have conscience.
> If you mean it's a torjan,yes,it WILL ENCRYPT ALL UR FILES AND FUCK UR ROOT USER.
> So can you stop here?Did I ask any bitcoin form U?If not,please GET OUT and stop POISONING issues by using Chinese rude words or Chinglish(DO U THINK I CANT UNDERSTAND CHINESE?) and egging me on to have a argument with others.
> Stop spamming,I beg U.

你理解错了，我英文不好我承认,我是说那个qq为17054536233的人说你的东西有木马病毒
我不这么认为呀，你的根本没有，你要去找他们理论呀，你的根本没病毒，他们说你的有病毒，这么严重的事情不找他们理论？好吧，这是你的作品，我不能做决定.

**Comment by ghost** [comment]
I DONT have the obligation to argue with someone(maybe your partner?) and make you laugh.
I dont mind what you think,I just do what I like.

**Comment by China-GWY** [comment]
行，你就想看到你的作品被别人诬陷

**Comment by l0nGYear** [comment]
> 行，你就想看到你的作品被别人诬陷

As a programmer, I think this is a very good project, but it is a pity that the developer of this project do not have the ability to lead this project. If you are also interested in such a project, I hope to work with you to develop a similar project.

In addition, I really can't stand the developer and want to say that we are all Chinese. If the language spoken on the international platform github is as disgusting as the qq group, I really feel very shameful.

**Comment by ghost** [comment]
> > 行，你就想看到你的作品被别人诬陷
> 
> As a programmer, I think this is a very good project, but it is a pity that the developer of this project do not have the ability to lead this project. If you are also interested in such a project, I hope to work with you to develop a similar project.
> 
> In addition, I really can't stand the developer and want to say that we are all Chinese. If the language spoken on the international platform github is as disgusting as the qq group, I really feel very shameful.

想象一下你花自己的时间维护的repo被一群中国人在qq群嘴臭，被某些人用于商业化用途后给你带来更多的什么都不懂，只会抱怨和嘴臭和黑屁的人，维护一个这样的耗费精力的东西谈何容易？
不管在哪里，想说中文想说英文都一样，想让谁看就让谁看，issue用中文一直rude words我个人认为并不妥当，所以英文issue一方面可以在爆粗之前think twice,一方面也能方便全世界的对这个repo感兴趣的人。
另外关于qq群内言论，一提起sponsor就有人拿百度网盘类比辱骂，就有人颅内假想拿钱跑路，群内同样还有人不清楚loader原理的情况下黑屁性能相关问题，同样还有人对指令用法的改变直接恶语相向？这全是qq群内，说中文的人的所作所为。不管是哪国人说什么语言，如果连什么是开源精神什么是sponsor都不知道的话，还是建议好心人另开幼稚园repo对直接对开源项目，对祖国同胞直接恶语相向的人进行教育启蒙:D

**Comment by ghost** [comment]
如果真觉得shameful的话请不要继续污染issue了，qq群随便你怎么喊，我屏蔽了谁都不影响

**Comment by l0nGYear** [comment]
> 如果真觉得shameful的话请不要继续污染issue了，qq群随便你怎么喊，我屏蔽了谁都不影响

I understand your difficulties, and I have encountered such problems in the development of my own projects. No matter how you choose to deal with them, I thank you for your previous contributions.
我理解您的困难之处，我在开发自己的项目的过程中也遇到过类似的问题。无论您选择如何应对他们，我都感谢您之前所作出的贡献。

**Comment by l0nGYear** [comment]
In addition, I want to apologize to you. I saw your language in the qq group and did not understand that you are trying to deal with those children in this way. To be honest, when I saw that you said those dirty words, I felt a bit inexplicable, but I don't think so now.

另外我想您道歉，我看到您在qq群里的语言，但没有理解您是试图通过这样的方式应对那些孩子们。实话说当我看到您qq说那些话的时候，我觉得有点愤怒，但我现在不会这样觉得了。

**Comment by l0nGYear** [comment]
> 如果真觉得shameful的话请不要继续污染issue了，qq群随便你怎么喊，我屏蔽了谁都不影响

In addition, I want to apologize to you. I saw your language in the qq group and did not understand that you are trying to deal with those children in this way. To be honest, when I saw that you said those dirty words, I felt a bit inexplicable, but I don't think so now.

另外我想您道歉，我看到您在qq群里的语言，但没有理解您是试图通过这样的方式应对那些孩子们。实话说当我看到您qq说那些话的时候，我觉得有点愤怒，但我现在不会这样觉得了。
