### ISSUE TITLE
land bug report

### ISSUE THREAD

**Issue by WangYneos** [Sysca11/bdlauncher#5]
有空格的玩家领域归属出问题

**Comment by WangYneos** [comment]
![screenshot_20190223-103155](https://user-images.githubusercontent.com/42824603/53280564-833c6800-3756-11e9-94e8-432c9253eeda.png)
玩家名是这个RED 007 LLer

**Comment by WangYneos** [comment]
可以麻烦解决一下吗

**Comment by Sysca11** [comment]
站在领地截图，破坏下东西截图

**Comment by Sysca11** [comment]
等下我看看

**Comment by WangYneos** [comment]
就是请勿破环的那个提示
加双引号也没用

**Comment by Sysca11** [comment]
你发下qq gayhub说话不方便

**Comment by WangYneos** [comment]
1431936880
