### ISSUE TITLE
Switch to XUID

### ISSUE THREAD

**Issue by Extollite** [Sysca11/bdlauncher#57]
When are you going to refactor mods and their commands, I propose to switch to XUIDs and do commands  case independent for players names. I mean when player use /money pay extollite 50 it should pay to Extollite if he exists on the server. And also I think it should be linked to player's XUIDs if they switch their name they would still have their money.

**Comment by mclauncherlinux** [comment]
yeah, a lot people paid in my smp server to wrong players then they complain and give me the fault xD. Pls switch to XUID, it would be awesome :)

**Comment by ghost** [comment]
use /money paygui instead

**Comment by HongyiMC** [comment]
@Sysca11 I think you missed his point

**Comment by ghost** [comment]
moved to #76
