### ISSUE TITLE
这是什么问题

### ISSUE THREAD

**Issue by SilveryLoong** [Sysca11/bdlauncher#60]
DEP obj/launcher_exec_server_release.d
 CC  obj/launcher_exec_server_release.o
cc: error: unrecognized command line option '-std=gnu17'; did you mean '-std=gnu11'?
Makefile:156: recipe for target 'obj/launcher_exec_server_release.o' failed
make: *** [obj/launcher_exec_server_release.o] Error 1

**Comment by KawaiiNahida** [comment]
升级gcc9
请

**Comment by SilveryLoong** [comment]
CC  obj/launcher_exec_server_release.o
cc: error: unrecognized command line option '-std=gnu17'; did you mean '-std=gnu11'?
Makefile:156: recipe for target 'obj/launcher_exec_server_release.o' failed
make: *** [obj/launcher_exec_server_release.o] Error 1

**Comment by SilveryLoong** [comment]
升级了

**Comment by ghost** [comment]
@SilveryLoong 参考https://bdl.mc114.top/zh/

**Comment by SilveryLoong** [comment]
Makefile:171: recipe for target 'mod/bossbar/bossbar.command.gen.cpp' failed
make: *** [mod/bossbar/bossbar.command.gen.cpp] Error 127
make: *** Deleting file 'mod/bossbar/bossbar.command.gen.cpp'

**Comment by SilveryLoong** [comment]
这又是啥

**Comment by ghost** [comment]
@SilveryLoong clang-format

**Comment by SilveryLoong** [comment]
不懂

**Comment by SilveryLoong** [comment]
MOD] inject to 0x55dc9946e200 pid 19457
[MOD] main,start loading mods
[MOD] loading ./mods/base.mod
[MOD] loading ./mods/opti.mod
[MOD] loading ./mods/command.mod
[MOD] loading ./mods/gui.mod
[MOD] loading ./mods/bear.mod
[MOD] loading ./mods/money.mod
[MOD] loading ./mods/protect.mod
[MOD] loading ./mods/killbonus.mod
[MOD] loading ./mods/cmdhelp.mod
[MOD] loading ./mods/cdk.mod
[MOD] loading ./mods/transfer.mod
[MOD] loading ./mods/tp.mod
[MOD] loading ./mods/land.mod
[MOD] loading ./mods/custname.mod
[MOD] loading ./mods/bossbar.mod
[MOD] start loading
enabling ./mods/base.mod
I [base:mod/base/base.cpp:309] fake vtable pt (nil) 0x55dc9e3e6360 0x55dc99dabb20 0x55dc99dabb20
I [base:mod/base/base.cpp:316] loaded! V2020-01-12
enabling ./mods/opti.mod
I [opti:mod/opti/main.cpp:45] * Line 1, Column 1
  Syntax error: value, object or array expected.

**Comment by SilveryLoong** [comment]
这是好了吗

**Comment by ShrBox** [comment]
config

**Comment by SilveryLoong** [comment]
要怎么做

**Comment by SilveryLoong** [comment]
![Screenshot_2020-01-22-12-56-01-455_com tencent mtt](https://user-images.githubusercontent.com/35058685/72866521-8415ab00-3cd3-11ea-8769-35fab1c71bd2.jpg)
是这个吗？要怎么做

**Comment by ghost** [comment]
@SilveryLoong 把config文件夹复制到服务器根目录

**Comment by SilveryLoong** [comment]
MOD] inject to 0x55c401e2d200 pid 2321
[MOD] main,start loading mods
[MOD] loading ./mods/base.mod
[MOD] loading ./mods/opti.mod
[MOD] loading ./mods/command.mod
[MOD] loading ./mods/gui.mod
[MOD] loading ./mods/bear.mod
[MOD] loading ./mods/money.mod
[MOD] loading ./mods/protect.mod
[MOD] loading ./mods/killbonus.mod
[MOD] loading ./mods/cmdhelp.mod
[MOD] loading ./mods/cdk.mod
[MOD] loading ./mods/transfer.mod
[MOD] loading ./mods/tp.mod
[MOD] loading ./mods/land.mod
[MOD] loading ./mods/custname.mod
[MOD] loading ./mods/bossbar.mod
[MOD] start loading
enabling ./mods/base.mod
I [base:mod/base/base.cpp:309] fake vtable pt (nil) 0x55c406da5360 0x55c40276ab20 0x55c40276ab20
I [base:mod/base/base.cpp:316] loaded! V2020-01-12
enabling ./mods/opti.mod
I [opti:mod/opti/main.cpp:50] FastMath enabled
I [opti:mod/opti/main.cpp:59] found 2464
I [opti:mod/opti/main.cpp:59] found 9480
I [opti:mod/opti/main.cpp:61] Warning!!!Broken patch dected.Wont Patch it!
I [opti:mod/opti/main.cpp:69] Warning!!!Broken patch dected.Wont Patch it!
I [opti:mod/opti/main.cpp:191] loaded! V2019-12-19
enabling ./mods/command.mod
enabling ./mods/gui.mod
I [gui:mod/gui/main.cpp:155] Loaded V2020-01-12
enabling ./mods/bear.mod
I [bear:mod/bear/main.cpp:565] Loaded V2020-01-12
enabling ./mods/money.mod
I [money:mod/money/main.cpp:206] loaded! V2020-01-12
[MOD] err loading ./mods/protect.mod handle (nil) ./mods/protect.mod: cannot open shared object file: No such file or directory

**Comment by SilveryLoong** [comment]
这又是什么鬼

**Comment by SilveryLoong** [comment]
是不是还有什么文件没有复制，这个复制是手动的吗

**Comment by ghost** [comment]
@SilveryLoong ci下载prebuilt binary,放到mods文件夹

**Comment by SilveryLoong** [comment]
在哪里下载

**Comment by SilveryLoong** [comment]
./bdlauncher: error while loading shared libraries: libreadline.so.8: cannot open shared object file: No such file or directory

**Comment by SilveryLoong** [comment]
我真的

**Comment by Redbeanw44602** [comment]
您好！请认真阅读"Install.md"上的表格。请不要继续污染Watcher们的邮箱，谢谢配合，感激不尽！

**Comment by SilveryLoong** [comment]
好吧，我已经搞好了
