### ISSUE TITLE
TODO upgrade to bedrock_server 1.14.20.1

### ISSUE THREAD

**Issue by KawaiiNahida** [Sysca11/bdlauncher#69]
除opti.mod外插件工作基本正常（未完整测试）
opti加载后会导致启动时段错误
Segmentation fault (core dumped)

**Comment by KawaiiNahida** [comment]
![图片](https://user-images.githubusercontent.com/42824603/73361849-b7ae9180-42e0-11ea-842b-4217653e60b2.png)
wsl下无法编译，无法运行gdb
（就算能编译我也不怎么会搞）
望大佬修复，谢谢

**Comment by ghost** [comment]
@WangYneos 装clang-format
