### ISSUE TITLE
add命令添加

### ISSUE THREAD

**Issue by KawaiiNahida** [Sysca11/bdlauncher#7]
if(origin.getOriginType()==0 && ((Player*)origin.getEntity())->getCommandPermissionLevel()<1) return;
        if(swith(oper,"add")){
          if(oper.size()>4){
            char buf[512];
            int nm;
            sscanf(oper.c_str()+4,"%s %d",buf,&nm);
			addMoney(string(buf),nm);
            outp.addMessage("add ok!");
            outp.success();
          }
        }

![image](https://user-images.githubusercontent.com/42824603/53679862-911d5a80-3d0d-11e9-9008-789be966c56a.png)

**Comment by ghost** [comment]
请pull request，谢谢

**Comment by KawaiiNahida** [comment]
ok
