### ISSUE TITLE
使用Custom Map时出错

### ISSUE THREAD

**Issue by Redbeanw44602** [Sysca11/bdlauncher#70]
1.使用img2bin转换图片，未出错，输出0.bin和1.bin
2.我把1.bin放到/mods文件夹内
3.手持空白地图(无定位器)在服务器内/map 1.bin
4,服务器成功崩溃（下图）
![3](https://user-images.githubusercontent.com/29711228/73375334-9ce71780-42f6-11ea-98ae-7987f9bec6e5.png)

BDS: 1.14.20.1
BDL: 2020.01.30 0:23时pull
OS: Debian10
其他Error: 根本没

希望dalao解决，custom map可以淦很多好玩的事情呢~

**Comment by KawaiiNahida** [comment]
map貌似没对新版更新
