### ISSUE TITLE
Changed max homes on an existing server=crash

### ISSUE THREAD

**Issue by salllaf** [Sysca11/bdlauncher#75]
1. Max homes were at "10" 
2. Switched to "15"
3. Player added 11th home, server crashed. 
4  Config switched back to "10"
5. All others can use /home 
6. This one player can't even use home or try to delete that home without the server crashing. Have tried putting the config back at 15 long enough for him to delete it, same crash. 

I've updated to your latest software and all other requirements are updated. 
OS: linux ubuntu 18.04 bionic beaver
Please see screenshot for crash errors and other info, thanks! (also thank you for providing this software and your hard work, the players enjoy it)
![Screenshot (199)](https://user-images.githubusercontent.com/40781950/73592861-ce194080-44cc-11ea-95ff-71a27dc5eb0b.png)

**Comment by ghost** [comment]
@salllaf There is a hard-coded limit (max=10).So if you created more than 10 homes,the behavior is undefined.
ways to solve this problem:
1.modify the source code,you can find the hard-coded limit 10 in 'struct homes'
2.I will fix this as soon as possible,but I'm sorry that I'm occupied with something important these days.
3.If you have a leveldb editor you can delete the abnormal home data.

**Comment by salllaf** [comment]
Awesome. I can work with this information, thank you. I've enjoyed figuring out most things on my own as you all have done a great job of posting information and replying to people. This one was beating me though ha ha. Thanks again!
